set shell := ['bash', '-uc']

[working-directory: 'model_conversion']
clean-model:
    rm -rf dist/MLC/* dist/libs/*.wasm

clean:
    rm -rf dist/

copy:
    mkdir -p dist/models/libs/ && cp model_conversion/dist/libs/* dist/models/libs/
    ls model_conversion/dist/MLC | xargs -i sh -c "mkdir -p dist/models/MLC/{}/resolve/main/ && cp model_conversion/dist/MLC/{}/* dist/models/MLC/{}/resolve/main/"
