set shell := ['bash', '-uc']

[working-directory: 'model_conversion']
clean-model:
    rm -rf dist/*-MLC dist/libs/*.wasm

clean-webserver:
    rm -rf dist/

copy-model model='gemma-3-1b-it':
    mkdir -p dist/models/{{model}}-q4f16_1-MLC/resolve/main/
    cp -r model_conversion/dist/{{model}}-q4f16_1-MLC/* dist/models/{{model}}-q4f16_1-MLC/resolve/main/
    cp model_conversion/dist/libs/*.wasm dist/models
